### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by lokst**
- Output test results in junit format and upload them as artifacts and populate the Test Summary view
- Use `npm install` instead of `npm ci` as `npm ci` seems to regenerate the node_modules directory even if it exists
- Add some comments to guide users who wish to adapt the config for usage with yarn
- Remove yarn.lock and Dockerfile for now as they are not used

### CODE REVIEW

**Comment by lokst** [comment]
Going ahead to merge this but please feel free to add on your revisions!

**Comment by lokst** [comment]
@jkzilla After more reading up I realize `npm ci` together with caching the npm cache as you originally had done might be even faster so feel free to restore those changes (together with making sure npm 6 is used)!

**Comment by iynere** [comment]
@lokst are we supposed to get this using orb syntax ? you can use the node orb's default executor, for example. or use any random executor and install node w/ the orb

**Comment by lokst** [comment]
Hi @iynere The goal of these PRs was to fix any issues in the current master branch (which does not currently use orbs) first. We could have orbs and non-orbs branches (one of them could be the master branch I guess) so that Server customers have something to reference too. Do you know if the node orb is ready to be used in the sample project?

**Comment by iynere** [comment]
@lokst the node orb is fine to be used right now, it could use more added to it but everything that's in it should be ok to use

**Pull request merged**
